apiVersion: batch/v1
kind: Job
metadata:
  name: frontend-job
spec:
  template:
    spec:
      containers:
      - name: frontend
        image: lsstts/love-frontend:develop
        command: [ "/bin/sh","-c", "cp -R /usr/src/love/ /usr/src/love-frontend" ]
        volumeMounts:
          - mountPath: "/usr/src"
            name: love-pv-storage
      restartPolicy: Never
      volumes:
        - name: love-pv-storage
          persistentVolumeClaim:
            claimName: love-pv-claim
