apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-deployment
spec:
  selector:
    matchLabels:
      app: jupyter-service
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter-service
    spec:
      containers:
      - name: jupyter
        image: lsstts/love-jupyter:develop
        ports:
        - containerPort: 1234
        volumeMounts:
          - mountPath: "/home/saluser/notebooks"
            name: love-jupyter-pv-storage
        env:
          - name: JUPYTER_PASS
            value: "jupyter"
          - name: LSST_DDS_PARTITION_PREFIX
            value: "lsstts"
      volumes:
         - name: love-jupyter-pv-storage
           persistentVolumeClaim:
             claimName: love-jupyter-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  selector:
    app: jupyter-service
  type: LoadBalancer
  ports:
    - port: 1234
      targetPort: 1234
      nodePort: 30001
