version: "3.7"

services:
  frontend:
    container_name: love-frontend-mount
    build:
      context: ${DOCKERFILE_PATH_FRONTEND}
      dockerfile: Dockerfile-dev
    image: love-frontend-image-mount
    # network_mode: ${NETWORK_NAME}
    ports:
      - "3000:3000"
    volumes:
      - ${DOCKERFILE_PATH_FRONTEND}:/usr/src/love
      - /usr/src/love/love/node_modules
    environment:
      CI: "true"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  styleguide:
    container_name: love-styleguide-mount
    build:
      context: ${DOCKERFILE_PATH_FRONTEND}
      dockerfile: Dockerfile-dev
    image: love-frontend-image-mount
    command: yarn guide:start
    # network_mode: ${NETWORK_NAME}
    ports:
      - "3001:3001"
    volumes:
      - ${DOCKERFILE_PATH_FRONTEND}:/usr/src/love
      - /usr/src/love/love/node_modules
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  nginx:
    container_name: love-nginx-mount
    image: nginx:1.13.1
    depends_on:
      - frontend
    # network_mode: ${NETWORK_NAME}
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
