version: "3.7"

services:
  frontend:
    container_name: love-frontend-mount
    build:
      context: ${DOCKERFILE_PATH_FRONTEND}
      dockerfile: docker/Dockerfile-dev
    image: love-frontend-image-mount
    network_mode: host
    volumes:
      - ${DOCKERFILE_PATH_FRONTEND}/love:/usr/src/love
      - /usr/src/love/node_modules
    environment:
      CI: "true"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  nginx:
    container_name: love-nginx-mount
    image: nginx:1.25.1
    network_mode: host
    depends_on:
      - frontend
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
