apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-ccarchiver-deployment
spec:
  selector:
    matchLabels:
      app: producer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
      - name: producer
        image: lsstts/love-producer:develop
        #resources
          #limits
            ##cpu: 128m
            ##memory: 128Mi
          #request:
            ##cpu: 128m
            ##memory: 128Mi
        ports:
        - containerPort: 5000
        #imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: love-producer-env
        env:
          - name: LOVE_CSC_PRODUCER
            value: "CCArchiver:0"

